# Generated by Django 3.2.6 on 2021-08-16 15:42

from django.db import migrations, models
import places.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyLocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', places.fields.PlacesField(max_length=255)),
            ],
        ),
    ]
